apiVersion: apps/v1
kind: Deployment
parameters:
  - name: CPU_MIN
    description: The required CPU size
    required: 50m
  - name: CPU_MAX
    description: The limit cpu size
    required: 500m
  - name: MEM_MIN
   description: The requested memory size
   required: 500m
metadata:
  name: my-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: my-angular-app
        image: narendrababulinux/mywebapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        resource:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 500Mi
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
