apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: my-angular-app
        image: narendrababulinux/mywebapp:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8085 
        resources:
          limits: 
            cpu: "128Mi"
            memory: "500m"
          requests:
            cpu: "64Mi"
            memory: "250Mi" 
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-services
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
